//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace AutoTransfer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Econ_D_YYYYMMDD
    {
        public string Processing_Date { get; set; }
        public string Product_Code { get; set; }
        public string Data_ID { get; set; }
        public string Year_Quartly { get; set; }
        public double PD_Quartly { get; set; }
        public Nullable<double> var1 { get; set; }
        public Nullable<double> var2 { get; set; }
        public Nullable<double> var3 { get; set; }
        public Nullable<double> var4 { get; set; }
        public Nullable<double> var5 { get; set; }
        public Nullable<double> var6 { get; set; }
        public Nullable<double> var7 { get; set; }
        public Nullable<double> var8 { get; set; }
        public Nullable<double> var9 { get; set; }
        public Nullable<double> var10 { get; set; }
        public Nullable<double> var11 { get; set; }
        public Nullable<double> var12 { get; set; }
        public Nullable<double> var13 { get; set; }
        public Nullable<double> var14 { get; set; }
        public Nullable<double> var15 { get; set; }
        public Nullable<double> var16 { get; set; }
        public Nullable<double> var17 { get; set; }
        public Nullable<double> var18 { get; set; }
        public Nullable<double> var19 { get; set; }
        public Nullable<double> var20 { get; set; }
        public Nullable<double> var21 { get; set; }
        public Nullable<double> var22 { get; set; }
        public Nullable<double> var23 { get; set; }
        public Nullable<double> var24 { get; set; }
        public Nullable<double> var25 { get; set; }
        public Nullable<double> var26 { get; set; }
        public Nullable<double> var27 { get; set; }
    
        public virtual Econ_Domestic Econ_Domestic { get; set; }
        public virtual Group_Product_Code_Mapping Group_Product_Code_Mapping { get; set; }
    }
}
