//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace AutoTransfer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Group_Product_Code_Mapping
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Group_Product_Code_Mapping()
        {
            this.Econ_D_YYYYMMDD = new HashSet<Econ_D_YYYYMMDD>();
        }
    
        public string Group_Product_Code { get; set; }
        public string Product_Code { get; set; }
        public System.DateTime Processing_Date { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Econ_D_YYYYMMDD> Econ_D_YYYYMMDD { get; set; }
    }
}
