using AutoTransfer.ViewModel;
using System.Collections.Generic;
using System.Linq;
using static AutoTransfer.Enum.Ref;

namespace AutoTransfer.CreateFile
{
    public class CreateA07File
    {
        /// <summary>
        /// create Put A07 File
        /// </summary>
        /// <param name="type"></param>
        /// <param name="dateTime"></param>
        public bool create(TableType type, string dateTime)
        {
            bool flag = false;

            try
            {
                List<string> data = new List<string>();

                SetFile f = new SetFile(type, dateTime);

                //ex: GetC03
                string getFileName = f.getA07FileName();

                #region File
                data.Add("START-OF-FILE");

                #region Title
                data.Add("FIRMNAME=dl221");
                data.Add("PROGRAMFLAG=oneshot");
                data.Add("FILETYPE=pc");
                data.Add($"REPLYFILENAME={getFileName}");
                data.Add("HIST_PERIOD=q");
                data.Add("PROGRAMNAME=gethistory");
                #endregion Title

                //空一行
                data.Add(string.Empty);

                data.Add("# Automatically generated by Bloomberg Data License Request Builder version 7.0.1");
                data.Add("# Build Code: 000000000000000148");

                //空一行
                data.Add(string.Empty);

                #region START-OF-FIELDS
                data.Add("START-OF-FIELDS");
                data.Add("NAME");
                data.Add("PX_LAST");
                data.Add("LAST_UPDATE_DT");
                data.Add("END-OF-FIELDS");
                #endregion START-OF-FIELDS

                //空一行
                data.Add(string.Empty);

                #region START-OF-DATA
                data.Add("START-OF-DATA");
                object obj = null;
                obj = new A07ViewModel();
                obj.GetType().GetProperties().ToList().ForEach(x => data.Add(x.Name + " Index"));
                data.Add("END-OF-DATA");
                #endregion START-OF-DATA

                data.Add("END-OF-FILE");
                #endregion File

                flag = new CreatePutFile().create(
                    f.putA07FilePath(),
                    f.putA07FileName(),
                    data);
            }
            catch
            {
                flag = false;
            }

            return flag;
        }
    }
}